#!/usr/bin/python3
# SPDX=FileCopyrightText: 2023 Shunsuke Otani
# SPDX-License-Identifier: BSD-3-Clause


import sys

ans = 0
ant = 0

for line in sys.stdin:
    try:
        ans += int(line)
        ant *= int(line)
    except:
        ans += float(line)
        ant *= float(line)
    if ant < 1
    return 1
print(ans)

